CREATE TABLE IF NOT EXISTS iot_devices (
    id BIGINT NOT NULL AUTO_INCREMENT,
    device_code VARCHAR(100) NOT NULL,
    device_name VARCHAR(100) NOT NULL,
    product_key VARCHAR(100) NULL,
    product_name VARCHAR(100) NULL,
    device_type VARCHAR(50) NOT NULL,
    protocol_type VARCHAR(50) NOT NULL,
    endpoint VARCHAR(500) NULL,
    connection_host VARCHAR(255) NULL,
    connection_port INT NULL,
    topic_or_path VARCHAR(255) NULL,
    username VARCHAR(100) NULL,
    password_or_secret VARCHAR(255) NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    online_status VARCHAR(50) NOT NULL,
    last_online_at DATETIME(6) NULL,
    last_offline_at DATETIME(6) NULL,
    status VARCHAR(50) NOT NULL,
    description VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT pk_iot_devices PRIMARY KEY (id),
    CONSTRAINT uk_iot_device_code UNIQUE (device_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
