CREATE TABLE IF NOT EXISTS iot_collection_tasks (
    id BIGINT NOT NULL AUTO_INCREMENT,
    task_name VARCHAR(100) NOT NULL,
    device_id BIGINT NOT NULL,
    device_code VARCHAR(100) NOT NULL,
    device_name VARCHAR(100) NOT NULL,
    product_key VARCHAR(100) NULL,
    product_name VARCHAR(100) NULL,
    collection_type VARCHAR(50) NOT NULL,
    schedule_type VARCHAR(50) NOT NULL,
    cron_expression VARCHAR(100) NULL,
    poll_interval_seconds INT NULL,
    source_type VARCHAR(50) NULL,
    data_format VARCHAR(50) NULL,
    config_json TEXT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    description VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT pk_iot_collection_tasks PRIMARY KEY (id),
    CONSTRAINT uk_iot_collection_task_name UNIQUE (task_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS iot_device_latest_telemetry (
    id BIGINT NOT NULL AUTO_INCREMENT,
    device_id BIGINT NOT NULL,
    device_code VARCHAR(100) NOT NULL,
    device_name VARCHAR(100) NOT NULL,
    product_key VARCHAR(100) NULL,
    product_name VARCHAR(100) NULL,
    metric_code VARCHAR(100) NOT NULL,
    metric_name VARCHAR(100) NOT NULL,
    metric_value VARCHAR(255) NOT NULL,
    value_type VARCHAR(50) NULL,
    unit VARCHAR(50) NULL,
    quality VARCHAR(50) NULL,
    collected_at DATETIME(6) NOT NULL,
    received_at DATETIME(6) NOT NULL,
    source_type VARCHAR(50) NULL,
    data_format VARCHAR(50) NULL,
    payload_json TEXT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT pk_iot_device_latest_telemetry PRIMARY KEY (id),
    CONSTRAINT uk_iot_device_latest_metric UNIQUE (device_id, metric_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS iot_device_telemetry_history (
    id BIGINT NOT NULL AUTO_INCREMENT,
    device_id BIGINT NOT NULL,
    task_id BIGINT NULL,
    device_code VARCHAR(100) NOT NULL,
    device_name VARCHAR(100) NOT NULL,
    product_key VARCHAR(100) NULL,
    product_name VARCHAR(100) NULL,
    metric_code VARCHAR(100) NOT NULL,
    metric_name VARCHAR(100) NOT NULL,
    metric_value VARCHAR(255) NOT NULL,
    value_type VARCHAR(50) NULL,
    unit VARCHAR(50) NULL,
    quality VARCHAR(50) NULL,
    collected_at DATETIME(6) NOT NULL,
    received_at DATETIME(6) NOT NULL,
    source_type VARCHAR(50) NULL,
    data_format VARCHAR(50) NULL,
    payload_json TEXT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT pk_iot_device_telemetry_history PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
